### ISSUE TITLE
v1.1.6 crash

### ISSUE THREAD

**Issue by renekliment** [vitas/beaconloc#18]
Hello there. 
I had version 1.1.5, which worked fine, however 1.1.6 crashes on launching the app.

Related log:
```
10-25 08:01:42.180  3569  6108 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.samebits.beacon.locator/.ui.activity.MainNavigationActivity (has extras)} from uid 10042
10-25 08:01:42.241  3569 24234 I ActivityManager: Start proc 22086:com.samebits.beacon.locator/u0a162 for activity com.samebits.beacon.locator/.ui.activity.MainNavigationActivity
10-25 08:01:42.347 22086 22086 I BeaconManager: BeaconManager started up on pid 22086 named 'com.samebits.beacon.locator' for application package 'com.samebits.beacon.locator'.  isMainProcess=true
10-25 08:01:42.352 22086 22086 D BeaconParser: Parsing beacon layout: m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25
10-25 08:01:42.396 22086 22086 W JobInfo : Specified interval for 1 is +5m10s0ms. Clamped to +15m0s0ms
10-25 08:01:42.396 22086 22086 W JobInfo : Specified flex for 1 is 0. Clamped to +5m0s0ms
10-25 08:01:42.396 22086 22086 W JobInfo : Specified interval for 1 is +5m10s0ms. Clamped to +15m0s0ms
10-25 08:01:42.396 22086 22086 W JobInfo : Specified flex for 1 is 0. Clamped to +5m0s0ms
10-25 08:01:42.397 22086 22086 D BeaconParser: Parsing beacon layout: s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19
10-25 08:01:42.398 22086 22086 D BeaconParser: Parsing beacon layout: s:0-1=feaa,m:2-2=10,p:3-3:-41,i:4-21v
10-25 08:01:42.399 22086 22086 D BeaconParser: Parsing beacon layout: m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25
10-25 08:01:42.399   420   420 E lowmemorykiller: Error writing /proc/22014/oom_score_adj; errno=22
10-25 08:01:42.400 22086 22086 D BeaconParser: Parsing beacon layout: m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25
10-25 08:01:42.400 22086 22086 D BeaconParser: Parsing beacon layout: m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24
10-25 08:01:42.400 22086 22086 D BeaconParser: Parsing beacon layout: m:0-3=4c000215,i:4-19,i:20-21,i:22-23,p:24-24
10-25 08:01:42.401 22086 22086 D BeaconLocator: Enable Background Scan
10-25 08:01:42.412 22086 22086 D BeaconLocator: Ignore Background scan, no regions
10-25 08:01:42.428  3569 10170 I ActivityManager: Process com.google.android.partnersetup (pid 22014) has died: fore TRNB
10-25 08:01:42.429  3569 10170 W ActivityManager: Scheduling restart of crashed service com.google.android.partnersetup/.InstalledAppJobService in 1000ms
10-25 08:01:42.491 22086 22086 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
10-25 08:01:42.591 22086 22104 D OpenGLRenderer: HWUI GL Pipeline
10-25 08:01:42.604 22086 22086 D AndroidRuntime: Shutting down VM
10-25 08:01:42.612 22086 22086 E AndroidRuntime: FATAL EXCEPTION: main
10-25 08:01:42.612 22086 22086 E AndroidRuntime: Process: com.samebits.beacon.locator, PID: 22086
10-25 08:01:42.612 22086 22086 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.samebits.beacon.locator/com.samebits.beacon.locator.ui.activity.MainNavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.samebits.beacon.locator.ui.adapter.BeaconAdapter.getItemCount()' on a null object reference
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.samebits.beacon.locator.ui.adapter.BeaconAdapter.getItemCount()' on a null object reference
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.DetectedBeaconsFragment.emptyListSetup(DetectedBeaconsFragment.java:149)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.DetectedBeaconsFragment.onCanScan(DetectedBeaconsFragment.java:177)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.ScanFragment.onBeaconServiceConnect(ScanFragment.java:154)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at org.altbeacon.beacon.BeaconManager.bind(BeaconManager.java:418)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.ScanFragment.onCreate(ScanFragment.java:60)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.DetectedBeaconsFragment.onCreate(DetectedBeaconsFragment.java:83)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreate(Fragment.java:2180)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1085)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:976)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.activity.BaseActivity.onStart(BaseActivity.java:134)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6992)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
10-25 08:01:42.612 22086 22086 E AndroidRuntime: 	... 9 more
10-25 08:01:42.615  3569 11147 W ActivityManager:   Force finishing activity com.samebits.beacon.locator/.ui.activity.MainNavigationActivity
10-25 08:01:42.622  3569 22105 W DropBoxManagerService: Dropping: data_app_crash (3245 > 0 bytes)
10-25 08:01:42.625  3569  3585 I ActivityManager: Showing crash dialog for package com.samebits.beacon.locator u0
10-25 08:01:43.118  3569  3584 W ActivityManager: Activity pause timeout for ActivityRecord{d9a796d u0 com.samebits.beacon.locator/.ui.activity.MainNavigationActivity t3267 f}
10-25 08:01:43.376  3569  3578 I zygote64: Background concurrent copying GC freed 159564(6MB) AllocSpace objects, 10(360KB) LOS objects, 42% free, 21MB/37MB, paused 427us total 131.646ms
10-25 08:01:43.443  3569  3584 I ActivityManager: Start proc 22107:com.google.android.partnersetup/u0a27 for service com.google.android.partnersetup/.InstalledAppJobService
```

Running this on Android 8.0.0, security patch 5th October 2017.

Thanks for having a look.

**Comment by vitas** [comment]
Hi, Could you try 1.1.7 apk release? thank you

**Comment by renekliment** [comment]
Unfortunately, I get another error:

```
10-29 09:54:16.934  3572  3898 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.samebits.beacon.locator/.ui.activity.MainNavigationActivity (has extras)} from uid 10042
10-29 09:54:17.211 10949 10949 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
10-29 09:54:17.295 10949 10949 D AndroidRuntime: Shutting down VM
10-29 09:54:17.305 10949 10949 E AndroidRuntime: FATAL EXCEPTION: main
10-29 09:54:17.305 10949 10949 E AndroidRuntime: Process: com.samebits.beacon.locator, PID: 10949
10-29 09:54:17.305 10949 10949 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.samebits.beacon.locator/com.samebits.beacon.locator.ui.activity.MainNavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewStub.setVisibility(int)' on a null object reference
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewStub.setVisibility(int)' on a null object reference
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.DetectedBeaconsFragment.emptyListSetup(DetectedBeaconsFragment.java:154)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.DetectedBeaconsFragment.onCanScan(DetectedBeaconsFragment.java:176)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.ScanFragment.onBeaconServiceConnect(ScanFragment.java:156)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at org.altbeacon.beacon.BeaconManager.bind(BeaconManager.java:418)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.ScanFragment.onCreate(ScanFragment.java:61)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.fragment.DetectedBeaconsFragment.onCreate(DetectedBeaconsFragment.java:81)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1187)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1070)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2374)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:781)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.activity.MainNavigationActivity.createOrResumeFragment(MainNavigationActivity.java:323)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.activity.MainNavigationActivity.addScanBeaconFragment(MainNavigationActivity.java:328)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.activity.MainNavigationActivity.launchScanBeaconView(MainNavigationActivity.java:389)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at com.samebits.beacon.locator.ui.activity.MainNavigationActivity.onCreate(MainNavigationActivity.java:127)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6975)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
10-29 09:54:17.305 10949 10949 E AndroidRuntime: 	... 9 more
10-29 09:54:17.308  3572  4230 W ActivityManager:   Force finishing activity com.samebits.beacon.locator/.ui.activity.MainNavigationActivity
10-29 09:54:17.315  3572  3587 I ActivityManager: Showing crash dialog for package com.samebits.beacon.locator u0
10-29 09:54:17.318  3572 12952 W DropBoxManagerService: Dropping: data_app_crash (3444 > 0 bytes)
10-29 09:54:17.812  3572  3586 W ActivityManager: Activity pause timeout for ActivityRecord{cde2e16 u0 com.samebits.beacon.locator/.ui.activity.MainNavigationActivity t3358 f}
```

**Comment by vitas** [comment]
[app-release.zip](https://github.com/vitas/beaconloc/files/1424918/app-release.zip)
Strange, cannot reproduce that. i have built another version to try out. Please, let me know if it works for you. thanks. the app ist attached by extension is renamed to .zip, just rename it back to app-release.apk.

**Comment by renekliment** [comment]
@vitas This version works :thumbsup:

**Comment by vitas** [comment]
great! thank you for the help
